export const styles = {
  root: {
    minHeight: "100vh",
    background:
      "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "center",
    padding: "24px 16px 48px",
    position: "relative",
    overflowX: "hidden",
  },
  starsLayer: {
    position: "fixed",
    inset: 0,
    pointerEvents: "none",
    zIndex: 0,
  },
  star: {
    position: "absolute",
    borderRadius: "50%",
    background: "#fff",
    animation: "twinkle 3s infinite ease-in-out",
  },
  menuWrap: {
    width: "100%",
    maxWidth: 480,
    zIndex: 1,
  },
  titleBlock: {
    textAlign: "center",
    marginBottom: 28,
    animation: "fadeIn 0.6s ease",
  },
  titleEmoji: {
    fontSize: 72,
    marginBottom: 10,
  },
  title: {
    fontSize: 42,
    fontWeight: 900,
    color: "#fff",
    letterSpacing: -1,
    textShadow: "0 2px 20px rgba(255,255,255,0.2)",
  },
  subtitle: {
    fontSize: 20,
    color: "rgba(255,255,255,0.6)",
    marginTop: 8,
    fontWeight: 600,
  },
  modeGrid: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: 12,
  },
  modeCard: {
    border: "2.5px solid",
    borderRadius: 20,
    padding: "18px 20px",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    transition: "transform 0.15s, box-shadow 0.15s",
    boxShadow: "0 4px 20px rgba(0,0,0,0.15)",
    fontFamily: "Nunito, sans-serif",
    cursor: "pointer",
    width: "100%",
  },
  modeEmoji: {
    fontSize: 32,
    flexShrink: 0,
  },
  modeLabel: {
    fontSize: 17,
    fontWeight: 800,
    textAlign: "left",
    lineHeight: 1.3,
  },
  gameWrap: {
    width: "100%",
    maxWidth: 480,
    zIndex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 16,
    animation: "fadeIn 0.4s ease",
  },
  gameHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backBtn: {
    background: "rgba(255,255,255,0.12)",
    border: "none",
    borderRadius: 12,
    color: "#fff",
    padding: "10px 16px",
    fontWeight: 700,
    fontSize: 15,
    cursor: "pointer",
  },
  scoreBox: {
    background: "rgba(255,255,255,0.15)",
    borderRadius: 14,
    padding: "10px 18px",
    color: "#fff",
    fontWeight: 800,
    fontSize: 20,
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  scoreNum: {
    fontSize: 24,
    color: "#FFD700",
  },
  scoreMax: {
    fontSize: 14,
    color: "rgba(255,255,255,0.5)",
  },
  questionCount: {
    background: "rgba(255,255,255,0.12)",
    borderRadius: 12,
    padding: "10px 16px",
    color: "#fff",
    fontWeight: 700,
    fontSize: 15,
  },
  timerBar: {
    height: 16,
    background: "rgba(255,255,255,0.1)",
    borderRadius: 10,
    position: "relative",
    overflow: "visible",
    display: "flex",
    alignItems: "center",
  },
  timerFill: {
    height: "100%",
    borderRadius: 10,
    position: "absolute",
    left: 0,
    top: 0,
  },
  timerText: {
    position: "absolute",
    right: -38,
    fontWeight: 800,
    fontSize: 14,
  },
  questionCard: {
    background: "#fff",
    borderRadius: 28,
    padding: "40px 24px",
    textAlign: "center",
    boxShadow: "0 10px 40px rgba(0,0,0,0.25)",
  },
  questionText: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    flexWrap: "wrap",
  },
  qNum: {
    fontSize: 68,
    fontWeight: 900,
    color: "#1a1a2e",
    lineHeight: 1,
  },
  qOp: {
    fontSize: 52,
    fontWeight: 900,
    color: "#4834D4",
  },
  qEq: {
    fontSize: 52,
    fontWeight: 900,
    color: "#888",
  },
  qAnswer: {
    fontSize: 68,
    fontWeight: 900,
    color: "#FF6B6B",
  },
  choicesWrap: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  choiceBtn: {
    borderRadius: 20,
    padding: "22px 24px",
    fontSize: 32,
    fontWeight: 900,
    transition: "transform 0.1s, box-shadow 0.1s",
    boxShadow: "0 4px 16px rgba(0,0,0,0.12)",
    cursor: "pointer",
  },
  modePill: {
    alignSelf: "center",
    borderRadius: 20,
    border: "2px solid",
    padding: "8px 18px",
    fontSize: 14,
    fontWeight: 700,
    opacity: 0.9,
  },
  resultWrap: {
    width: "100%",
    maxWidth: 480,
    zIndex: 1,
    animation: "fadeIn 0.5s ease",
  },
  resultCard: {
    background: "#fff",
    borderRadius: 28,
    padding: "36px 24px",
    boxShadow: "0 16px 50px rgba(0,0,0,0.3)",
    textAlign: "center",
  },
  trophyEmoji: {
    fontSize: 80,
    marginBottom: 10,
  },
  resultTitle: {
    fontSize: 38,
    fontWeight: 900,
    color: "#1a1a2e",
    marginBottom: 24,
  },
  resultStats: {
    display: "flex",
    justifyContent: "center",
    gap: 16,
    marginBottom: 24,
  },
  statBox: {
    background: "#F5F5F5",
    borderRadius: 16,
    padding: "16px 20px",
    minWidth: 90,
  },
  statVal: {
    fontSize: 32,
    fontWeight: 900,
    color: "#1a1a2e",
  },
  statLabel: {
    fontSize: 13,
    fontWeight: 700,
    color: "#888",
    marginTop: 4,
  },
  answerList: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    marginBottom: 24,
    maxHeight: 320,
    overflowY: "auto",
    textAlign: "left",
  },
  answerRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    borderRadius: 12,
    padding: "12px 14px",
    fontSize: 16,
    fontWeight: 700,
  },
  answerIcon: {
    fontSize: 20,
    flexShrink: 0,
  },
  answerQ: {
    flex: 1,
    color: "#333",
  },
  answerWrong: {
    color: "#C0392B",
    fontSize: 14,
    fontWeight: 800,
  },
  answerTime: {
    color: "#888",
    fontSize: 13,
    fontWeight: 700,
    marginLeft: 4,
  },
  resultBtns: {
    display: "flex",
    gap: 12,
    justifyContent: "center",
  },
  playAgainBtn: {
    background: "#4834D4",
    color: "#fff",
    border: "none",
    borderRadius: 16,
    padding: "16px 28px",
    fontSize: 17,
    fontWeight: 800,
    boxShadow: "0 4px 16px rgba(72,52,212,0.35)",
    cursor: "pointer",
  },
  menuBtn: {
    background: "#F5F5F5",
    color: "#333",
    border: "none",
    borderRadius: 16,
    padding: "16px 28px",
    fontSize: 17,
    fontWeight: 800,
    cursor: "pointer",
  },
};
